# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UnitTestSwiftCourse' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UnitTestSwiftCourse

  target 'UnitTestSwiftCourseTests' do
    inherit! :search_paths
    pod 'MockingbirdFramework', '~> 0.13'
  end

end
